x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "1.0.0"
  images:
    "":
      properties:
        image.repository:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG
    preflight-addon-tester:
      properties:
        apptest.image.repository:
          type: REPO_WITH_REGISTRY
        apptest.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
    default: glassbox-ipfto-addon-test

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
    default: glassbox-ipfto-addon-test

  install.serviceAccountName:
    type: string
    default: gbx-ipfto-runner

  install.configMapName:
    type: string
    default: gbx-ipfto-addon

  apptest.enabled:
    type: boolean
    default: true

required:
  - name
  - namespace
