{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.install.serviceAccountName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "glassbox-ipfto-addon.labels" . | nindent 4 }}
    app.kubernetes.io/component: addon-ipfto
  {{- with .Values.install.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
