apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "glassbox-ipfto-screening.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "glassbox-ipfto-screening.labels" . | nindent 4 }}
  {{- $annotations := dict -}}
  {{- if .Values.workloadIdentity.enabled }}
  {{- $_ := set $annotations "iam.gke.io/gcp-service-account" .Values.workloadIdentity.gcpServiceAccount -}}
  {{- end }}
  {{- range $key, $value := .Values.serviceAccount.annotations }}
  {{- $_ := set $annotations $key $value -}}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
