x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "1.0.0"
  images:
    glassbox-ipfto:
      properties:
        image.repository:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG
    glassbox-ipfto/ubbagent:
      properties:
        billing.ubbagent.image.repository:
          type: REPO_WITH_REGISTRY
        billing.ubbagent.image.tag:
          type: TAG
    glassbox-ipfto/tester:
      properties:
        apptest.image.repository:
          type: REPO_WITH_REGISTRY
        apptest.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
    default: glassbox-ipfto-test

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
    default: glassbox-ipfto-test

  config.executionMode:
    type: string
    default: standalone

  config.projectId:
    type: string
    default: verification_project

  config.ipftoMode:
    type: string
    default: phase2a_only

  config.failClosed:
    type: boolean
    default: true

  job.enabled:
    type: boolean
    default: false

  storage.type:
    type: string
    default: pvc

  storage.pvc.size:
    type: string
    default: 30Gi

  storage.pvc.storageClassName:
    type: string
    default: ""
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

required:
  - name
  - namespace
